### ISSUE TITLE
Choose a color for the website

### ISSUE THREAD

**Issue by sblaplace** [head-space/site#1]
As with every website, we need a color palette. Usually, when I look for color palettes, my instinct is to reach for the [Google material design guidelines](https://material.google.com/style/color.html#color-color-palette). I was also thinking about going with a nice blue color as the main color for the website.

**Comment by inflictedknight** [comment]
tbh i think blue or green would b the best. i don't rly like green as much so my instinct is blue as well, esp with going with google's material design guidelines you can't rly go wrong

**Comment by sblaplace** [comment]
Blue sounds perfect ^_^ Thanks, @inflictedknight
